### ISSUE TITLE
Отсутствует изображение

### ISSUE THREAD

**Issue by solnurkarim** [Cellyco/html-layout-test#1]
Отсутствует сплэш-изображение под мобильную версию страницы авторизации.

**Comment by solnurkarim** [comment]
Также изображения не соответствуют качеству тех, что были использованы для создания прототипов: сильно размываются при размере в 1мб.

**Comment by korney197823** [comment]
Я сам изображение сделал из большого, не проблема.............а вот как работает скрипт авторизации, и какие еще зависимости надо подтянуть кроме jquery непонятно

**Comment by shvyrev** [comment]
Спасибо пофиксил - https://s.mail.ru/K3eg/R4ot7vid4

Господа, обратите пожалуйста внимание. Менеджер оценивает по верстке стилям и шрифтам. Напишите ему на почту sales@cellyco.com. Он вас подключит к InVision оттуда можно скопировать и стили и шрифты.

На авторизацию не смотрит.

Спасибо.
